# Generated by Django 5.0.4 on 2024-04-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_juego', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='juegos/')),
            ],
        ),
    ]
