# Generated by Django 5.0.4 on 2024-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=40)),
                ('clave', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=3)),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
    ]
